# This is a basic workflow to fetch and merge upstream repo

name: CI-JOB

# Controls when the workflow will run
on:
  # Triggers the workflow according to schedule
  schedule:
    - cron : '1 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PEM: ${{ secrets.PEM_FILE }}
  APP_ID: ${{ secrets.APP_ID }}
  INSTALLATION_ID: ${{ secrets.INSTALLATION_ID }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "fetchAndMerge"
  fetchAndMerge:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Read from github secrets and store to a file
        run: |
          echo import certificate from secrets and regenerate the file
          echo $PEM | base64 -d > file.pem

      # Runs a single command using the runners shell
      - name: Run index.js script to run fetch and merge api on every repository where the app is installed
        run: node index.js ${APP_ID} ${INSTALLATION_ID}